2024-09-10 17:53:10,764	WARNING	Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\python\urban\module12\tests12_4.py", line 39, in test_run
    runner = Runner(False)
             ^^^^^^^^^^^^^
  File "C:\python\urban\module12\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано bool
2024-09-10 17:53:10,766	WARNING	Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\python\urban\module12\tests12_4.py", line 26, in test_walk
    walker = Runner('Johnnie Walker', -1)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python\urban\module12\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -1
